@hostname = 127.0.0.1
@port = 8000
@serviceUrl = http://{{hostname}}:{{port}}
@baseUrl = http://{{hostname}}:{{port}}
###
GET {{baseUrl}}/

###
GET {{baseUrl}}/user
###

POST {{baseUrl}}/user
Content-Type: application/json

{
    "fname": "yungi",
    "lname": "min",
    "email": "min.yunggi@example.com",
    "phone": 1235323456,
    "address": "123 Main St, Cityville"
}
###

PUT {{baseUrl}}/user/3
Content-Type: application/json

{
    "fname": "hoseok",
    "lname": "Jung",
    "email": "jung.hoseok@example.com",
    "phone": 1232748272,
    "address": "123 Main St, Cityville"

}
###

DELETE {{baseUrl}}/user/2

###
GET {{baseUrl}}/admin
###
POST {{baseUrl}}/admin
Content-Type: application/json

{
    "fname": "hoseok",
    "lname": "Jung",
    "email": "jung.hoseok@example.com",
    "phone": 1232748272,
    "address": "123 Main St, Cityville"

}
###
PUT {{baseUrl}}/admin/2
Content-Type: application/json

{
    "fname": "yungi",
    "lname": "min",
    "email": "min.yunggi@example.com",
    "phone": 1235323456,
    "address": "123 Main St, Cityville"
}
###
DELETE {{baseUrl}}/admin/1
###


GET {{baseUrl}}/post
###
POST {{baseUrl}}/post
Content-Type: application/json

{
    "title": "จจส.เดือด",
    "content": "อคคตสึ ยูตะหร่อมาก"
    
}
###
PUT {{baseUrl}}/post/3
Content-Type: application/json

{
    "title": "จจส.สุดเดือด",
    "content": "อคคตสึ ยูตะหร่อมากค่ะ"
}
###
DELETE {{baseUrl}}/post/1
###

GET {{baseUrl}}/post/1
###
POST {{baseUrl}}/post/1/comment
Content-Type: application/json

{
    "content":"อคคตสึ ยูตะหร่อมาก"
}
###
PUT {{baseUrl}}/post/1/comment/2
Content-Type: application/json
{
    "comment_name":"อคคตสึ ยูตะหร่อมากค่ะ"
}
###
